-- Add recurring task support to tasks table

-- Add new columns for recurring tasks
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_recurring BOOLEAN DEFAULT FALSE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence_pattern TEXT CHECK (recurrence_pattern IN ('daily', 'weekly', 'monthly'));
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence_start_date DATE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence_end_date DATE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS parent_task_id UUID REFERENCES tasks(id) ON DELETE CASCADE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence_day_of_week INTEGER CHECK (recurrence_day_of_week >= 0 AND recurrence_day_of_week <= 6); -- 0=Sunday, 6=Saturday

-- Create index for recurring task queries
CREATE INDEX IF NOT EXISTS idx_tasks_is_recurring ON tasks(is_recurring);
CREATE INDEX IF NOT EXISTS idx_tasks_parent_task_id ON tasks(parent_task_id);
CREATE INDEX IF NOT EXISTS idx_tasks_recurrence_dates ON tasks(recurrence_start_date, recurrence_end_date);

-- Create a function to generate recurring task instances
CREATE OR REPLACE FUNCTION generate_recurring_task_instances()
RETURNS TRIGGER AS $$
BEGIN
  -- Only generate instances for new recurring tasks (not for instances themselves)
  IF NEW.is_recurring = TRUE AND NEW.parent_task_id IS NULL THEN
    -- Instances will be generated by the application layer
    -- This trigger just ensures the parent task is set up correctly
    NEW.status := 'todo';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing trigger if it exists
DROP TRIGGER IF EXISTS generate_recurring_instances ON tasks;

-- Create trigger for recurring tasks
CREATE TRIGGER generate_recurring_instances
  AFTER INSERT ON tasks
  FOR EACH ROW
  EXECUTE FUNCTION generate_recurring_task_instances();

-- Add RLS policy for recurring tasks (same as regular tasks)
CREATE POLICY IF NOT EXISTS "Managers can create recurring tasks" ON tasks FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('manager', 'admin'))
);
